version: '3.0'
services:
  streetmerchant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
