version: '3.0'
services:
  redis:
    image: redis:alpine
    container_name: streetmerchant-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  streetmerchant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
    command: ["node", "server.js"]
    depends_on:
      - redis
